### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by trixr4kdz**
I didn't have time so I'll just leave the query here for now @dondi

### CODE REVIEW

**Comment by dondi** [comment]
OK, so to make sure I’m clear on this: the special query that is in this pull request is:
- Complete and correct (i.e., it gets all the extras)
- But *solely* needs to have duplicates removed
Is that correct? Let me know so I know how to approach it. Thanks!

**Comment by trixr4kdz** [comment]
Yes, it's correct. I believe it captures about 3200 genes but only 92 are new.

**Comment by dondi** [comment]
And there was no other condition you can spot, whether regex or something peculiar about the tags and attributes, that can differentiate the 92 from the rest?

**Comment by trixr4kdz** [comment]
Nothing that would distinguish them really come up. I tried to check if the ones with dbReference="STRING" would lessen the number but it still gave me about 2900 genes, and this actually removed some that weren't duplicated. I even tried with the dbReference id starting with "198214.", but that didn't work either.

**Comment by dondi** [comment]
Got it. That’s how it goes sometimes. Will let you know when I have something.

**Pull request merged**
